# Generated by Django 5.2.2 on 2025-07-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCrucero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printing_date', models.DateField()),
                ('supplier', models.CharField(max_length=200)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('service_date', models.DateField()),
                ('ship', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('terminal', models.CharField(blank=True, max_length=50)),
                ('sign', models.CharField(max_length=20)),
                ('excursion', models.CharField(max_length=200)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('pax', models.PositiveIntegerField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['service_date', 'ship', 'sign'],
            },
        ),
        migrations.AddField(
            model_name='pedidocrucero',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pedidocrucero',
            name='terminal',
            field=models.CharField(blank=True, max_length=50),
        ),

        migrations.AddField(
            model_name='pedido',
            name='tipo_servicio',
            field=models.CharField(choices=[('mediodia', 'Medio día'), ('dia_Completo', 'Día completo'), ('circuito', 'Circuito'), ('crucero', 'Crucero')], default='mediodia', max_length=15),
        ),
    ]
