# Generated by Django 5.2.2 on 2025-07-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedidocrucero_pedido_tipo_servicio'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pedidocrucero',
            constraint=models.UniqueConstraint(fields=('service_date', 'ship', 'sign'), name='uniq_servdate_ship_sign'),
        ),
    ]
