# Generated by Django 5.2.2 on 2025-07-16 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedidocrucero_uniq_servdate_ship_sign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidocrucero',
            options={'ordering': (['service_date', 'ship', 'sign'],)},
        ),
    ]
