# Generated by Django 5.2.2 on 2025-07-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedidocrucero_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidocrucero',
            options={'ordering': ['service_date', 'ship', 'sign'], 'verbose_name': 'Pedido Crucero', 'verbose_name_plural': 'Pedidos Cruceros'},
        ),
        migrations.RemoveConstraint(
            model_name='pedidocrucero',
            name='uniq_servdate_ship_sign',
        ),
        migrations.AlterUniqueTogether(
            name='pedidocrucero',
            unique_together={('service_date', 'ship', 'sign')},
        ),
    ]
