# Generated by Django 5.2.2 on 2025-07-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_pedidocrucero_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pedidocrucero',
            unique_together={('service_date', 'ship', 'sign', 'status')},
        ),
    ]
