# Generated by Django 5.2.2 on 2025-08-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedidocrucero_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidocrucero',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='pedidocrucero',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pedidocrucero',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='pedidocrucero',
            constraint=models.UniqueConstraint(fields=('service_date', 'ship', 'sign'), name='uniq_service_ship_sign'),
        ),
    ]
