# Generated by Django 5.2.2 on 2025-08-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_dedupe_before_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidocrucero',
            options={},
        ),
        migrations.AlterField(
            model_name='pedidocrucero',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
