# Generated by Django 5.2.2 on 2025-08-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_uniq_service_ship_sign'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pedidocrucero',
            name='uniq_service_ship_sign',
        ),
        migrations.AddIndex(
            model_name='pedidocrucero',
            index=models.Index(fields=['service_date', 'ship'], name='idx_ship_date'),
        ),
        migrations.AddConstraint(
            model_name='pedidocrucero',
            constraint=models.UniqueConstraint(fields=('service_date', 'ship'), name='uniq_service_ship'),
        ),
    ]
