# Generated by Django 5.2.2 on 2025-08-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_remove_pedidocrucero_uniq_service_ship_sign_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pedidocrucero',
            name='uniq_service_ship',
        ),
    ]
