# Generated by Django 5.2.2 on 2025-08-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_pedidocrucero_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidocrucero',
            options={'ordering': ['-updated_at', '-uploaded_at']},
        ),
        migrations.AlterUniqueTogether(
            name='pedidocrucero',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pedidocrucero',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
