# Generated by Django 5.2.2 on 2025-10-03 08:31
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0010_alter_pedidocrucero_options_and_more"),
    ]

    operations = [
        # Meta (ordering) – ok como está
        migrations.AlterModelOptions(
            name="pedidocrucero",
            options={"ordering": ["-updated_at", "-uploaded_at"]},
        ),

        # ⚠️ Solo cambiamos el estado de unique_together (no tocar BD)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="pedidocrucero",
                    unique_together=set(),
                ),
                # Si también tuvieses AlterIndexTogether, hazlo aquí igual.
            ],
            database_operations=[
                # vacío a propósito: no borres constraints inexistentes en la BD
            ],
        ),

        # Estos sí deben aplicarse en BD
        migrations.AddField(
            model_name="pedido",
            name="fecha_modificacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="updates",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
