# Generated by Django 5.2.2 on 2025-10-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0010_alter_pedidocrucero_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pedidocrucero",
            options={"ordering": ["-updated_at", "-uploaded_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="pedidocrucero",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="pedido",
            name="fecha_modificacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="updates",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
