# Generated by Django 5.2.2 on 2025-10-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0013_emisores_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="emisores",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
